# permissions for end users to edit rsyncs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rsync-editor-role
rules:
- apiGroups:
  - populator.volume.konveyor.dev
  resources:
  - rsyncs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - populator.volume.konveyor.dev
  resources:
  - rsyncs/status
  verbs:
  - get
